
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="/">Ínicio</a></li>
            <li><a href="/escola/instituicao">Cadastro de Instituição</a></li>
            <li class="active">Salvar</li>
        </ol>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h1><i class="icon icon-group"></i> Cadastro <small>de instituição</small></h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>Salvar</b>
                </div>

                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                            $this->form->prepare();
                            echo $this->form()->openTag($form);
                            $id = $this->form->get('id');
                            $nome = $this->form->get('nome');
                            $responsavel = $this->form->get('responsavel');
                            $ativo = $this->form->get('ativo');
                            $telefones = $this->form->get('telefones');

                            /*
                             * begin enderecoExterno form fieldset
                             */
                            $enderecoExterno = $this->form->get('enderecoExterno');
                            $idEnderecoExterno = $enderecoExterno->get('id');
                            $cep = $enderecoExterno->get('cep');
                            $tipoLogradouro = $enderecoExterno->get('tipoLogradouro');
                            $logradouro = $enderecoExterno->get('logradouro');
                            $numero = $enderecoExterno->get('numero');
                            $cidade = $enderecoExterno->get('cidade');
                            $bairro = $enderecoExterno->get('bairro');
                            $uf = $enderecoExterno->get('siglaUf');
                            $letra = $enderecoExterno->get('letra');
                            $apartamento = $enderecoExterno->get('apartamento');
                            $bloco = $enderecoExterno->get('bloco');
                            $andar = $enderecoExterno->get('andar');
                            $zonaLocalizacao = $enderecoExterno->get('zonaLocalizacao');
                            $complemento = $enderecoExterno->get('complemento');

                            echo $this->formInput($id);
                            echo $this->formInput($idEnderecoExterno);
                            ?>
                            <br>

                            <div class="form-group required">
                                <label for="nome">
                                    <?php
                                    echo $nome->getOption('label');
                                    ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-6">
                                        <?php
                                        echo $this->formInput($nome);
                                        ?>
                                        <span class="help-block">
                                                <?php
                                                echo $this->formElementErrors($nome);
                                                ?>
                                            </span>
                                    </div>
                                </div>
                            </div>


                            <div class="form-group">
                                <label for="responsavel">
                                    <?php
                                    echo $responsavel->getOption('label');
                                    ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-6">
                                        <?php
                                        echo $this->formInput($responsavel);
                                        echo $this->formElementErrors($responsavel);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="cep">
                                    <?php echo $cep->getOption('label');?>
                                </label>
                                <div class="row">
                                    <div class="col-md-1">
                                        <?php
                                        echo $this->formInput($cep);
                                        echo $this->formElementErrors($cep);
                                        ?>
                                    </div>
                                    <div class="col-md-3 ceploading"
                                         style="padding-left:25px; padding-top:4px; display:none;">
                                        <i class='glyphicon icon-spinner icon-spin icon-large'></i>
                                        Pesquisando CEP, aguarde!
                                    </div>

                                </div>
                            </div>
                            <div class="form-group">
                                <label for="tipoLogradouro">
                                    <?php
                                    echo $tipoLogradouro->getOption('label');
                                    ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        echo $this->formSelect($tipoLogradouro);
                                        echo $this->formElementErrors($tipoLogradouro);
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="logradouro">
                                    <?php echo $logradouro->getOption('label'); ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-5">
                                        <?php
                                        echo $this->formInput($logradouro);
                                        echo $this->formElementErrors($logradouro);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="numero">
                                    <?php echo $numero->getOption('label'); ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-2">
                                        <?php
                                        echo $this->formInput($numero);
                                        echo $this->formElementErrors($numero);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="complemento">
                                    <?php echo $complemento->getOption('label'); ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-5">
                                        <?php
                                        echo $this->formInput($complemento);
                                        echo $this->formElementErrors($complemento);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="letra">
                                    <?php echo $letra->getOption('label'); ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-1">
                                        <?php
                                        echo $this->formInput($letra);
                                        echo $this->formElementErrors($letra);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="apartamento">
                                    <?php echo $apartamento->getOption('label');?>
                                </label>
                                <div class="row">
                                    <div class="col-md-1">
                                        <?php
                                        echo $this->formInput($apartamento);
                                        echo $this->formElementErrors($apartamento);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="bloco">
                                    <?php echo $bloco->getOption('label');?>
                                </label>
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        echo $this->formInput($bloco);
                                        echo $this->formElementErrors($bloco);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="andar">
                                    <?php echo $andar->getOption('label');?>
                                </label>
                                <div class="row">
                                    <div class="col-md-1">
                                        <?php
                                        echo $this->formInput($andar);
                                        echo $this->formElementErrors($andar);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="bairro">
                                    <?php echo $bairro->getOption('label');?>
                                </label>
                                <div class="row">
                                    <div class="col-md-5">
                                        <?php
                                        echo $this->formInput($bairro);
                                        echo $this->formElementErrors($bairro);
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="zonaLocalizacao">
                                    <?php
                                    echo $zonaLocalizacao->getOption('label');
                                    ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        echo $this->formSelect($zonaLocalizacao);
                                        echo $this->formElementErrors($zonaLocalizacao);
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="cidade">
                                    <?php echo $cidade->getOption('label'); ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-5">
                                        <?php
                                        echo $this->formInput($cidade);
                                        echo $this->formElementErrors($cidade);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="uf">
                                    <?php
                                    echo $uf->getOption('label');
                                    ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        echo $this->formSelect($uf);
                                        echo $this->formElementErrors($uf);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <!-- telefones -->
                            <!--                                <div class="form-group">-->
                            <?php
                            //echo $this->formCollection($form->get('telefones'));
                            ?>
                            <!--                                </div>-->
                            <div class="form-group">

                                <label for="telefones">
                                    <?php
                                    echo $telefones->getOption('label');
                                    ?>
                                </label>

                            </div>

                            <?php
                            foreach ($telefones as $telefone) {
                                echo $this->formInput($telefone->get('id'));
                                ?>
                                <div class="row">
                                    <div class="form-group">

                                        <div class="col-md-1 form-group">
                                            <label for="<?php echo $telefone->get('numero')->getOption('label');?>">
                                                <?php echo $telefone->get('ddd')->getOption('label');?></label>

                                            <div class="row">
                                                <div class="col-md-12">
                                                    <?php
                                                    echo $this->formInput($telefone->get('ddd'));?>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-2 form-group">
                                            <label for="<?php echo $telefone->get('numero')->getOption('label');?>">
                                                <?php echo $telefone->get('numero')->getOption('label');?>
                                            </label>

                                            <div class="row">
                                                <div class="col-md-12">
                                                    <?php
                                                    echo $this->formInput($telefone->get('numero'));?>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>

                                <?php
                            }
                            ?>

                            <div class="form-group">
                                <label for="ativo">
                                    <?php
                                    echo $ativo->getOption('label');
                                    ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        echo $this->formSelect($ativo);
                                        echo $this->formElementErrors($ativo);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <br>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        $enviar = $this->form->get('submit');
                                        echo $this->formElement($enviar);
                                        ?>
                                    </div>
                                </div>
                            </div>



                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<?php
echo $this->headLink()->prependStylesheet($this->basePath() . '/componentes/chosen/chosen.css');
echo $this->headScript()->prependFile($this->basePath() . '/componentes/chosen/chosen.jquery.min.js', 'text/javascript');
echo $this->headScript()->prependFile($this->basePath()
    . '/componentes/jquery.masked-input/jquery.maskedinput.min.js');
?>
<script type="text/javascript">
    var config = {
        '.chosen-select'           : {},
        '.chosen-select-deselect'  : {allow_single_deselect:true},
        '.chosen-select-no-single' : {disable_search_threshold:10},
        '.chosen-select-no-results': {no_results_text:'Oops, nada foi encontrado!'},
        '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
        $(selector).chosen(config[selector]);
    }

    $(document).ready(function() {


        jQuery(function($){

            $(".cep").mask("99999-999");
            //mask data documento
            $(".ddd").mask("99?9");

            //$(".numero").mask('9999-9999');
            $('.numero-telefone').focusout(function(){
                var phone, element;
                element = $(this);
                element.unmask();
                phone = element.val().replace(/\D/g, '');
                if(phone.length > 8) {
                    element.mask("99999-999?9");
                } else {
                    element.mask("9999-9999?9");
                }
            }).trigger('focusout');


        });

        var last_cep = 0;

        $('.cep').on('keyup', function(){
            var cep = $.trim($('.cep').val()).replace('_','');
            if(cep.length >= 9){
                if(cep != last_cep){
                    busca();
                    last_cep = cep;
                }
            }
        });

        function busca(){
            var cep = $('.cep').val();
            $.ajax({
                url: '/core/cep/index/value/' + cep,
                dataType: "json",
                beforeSend : function(){
                    $(".ceploading").show();
                },
                success : function(data){
                    $(".cidade").val("");
                    $(".logradouro").val("");
                    $(".bairro").val("");
                    $('.uf').val('').trigger('chosen:updated');
                    $('.tipoLogradouro').val('').trigger('chosen:updated');
                    //$('.uf').find('option:first-child').prop('selected', true).end().trigger('liszt:updated');
                    if (typeof data.length == "undefined"){
                        //limpando os dados

                        if (data.id){
                            // console.log(data.id);
                        }
                        if (data.cep){
                            // console.log(data.cep);
                        }
                        if (data.nome){
                            $(".cidade").val(data.nome);
                            //$(".logradouro").focus();
                            $(".tipoLogradouro").trigger('chosen:activate');
                        }
                        if (data.cidade){
                            $(".cidade").val(data.cidade);
                        }
                        if (data.logradouro){
                            $(".logradouro").val(data.logradouro);
                            $(".numero").focus();
                        }
                        if (data.bairro){
                            $(".bairro").val(data.bairro);
                        }
                        if (data.tipoLogradouro){

                        }
                        if (data.uf){

                        }
                        if (data.nomeSemAcento){

                        }
                        if (data.idEstado){
                            //tem estado escolher o estado no select :D
                            $('.uf').val(data.idEstado).trigger('chosen:updated');
                        }
                        if (data.idTipoLogradouro) {
                            $('.tipoLogradouro').val(data.idTipoLogradouro).trigger('chosen:updated');
                        }
                    } else {
                        decisao = confirm("CEP! Não encontrado na base de dados!, Deseja digitar novamente o CEP? Clique no botão OK");
                        if (decisao){
                            $(".cep").val("");
                            $(".cep").focus();
                            last_cep = 0;
                        } else {
                            $(".logradouro").focus();
                        }
                    }
                },
                complete: function(){
                    $(".ceploading").hide();
                }
            });

        }

    });
    //end document ready function
</script>