<?php

namespace DoctrineORMModule\Proxy\__CG__\Usuario\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fisica extends \Usuario\Entity\Fisica implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'dataNasc', 'sexo', 'dataUniao', 'dataObito', 'nacionalidade', 'dataChegadaBrasil', 'ultimaEmpresa', 'nomeMae', 'nomePai', 'nomeConjuge', 'nomeResponsavel', 'justificativaProvisorio', 'refCodSistema', 'cpf', 'pessoaMae', 'pessoaPai', 'pessoaResponsavel', 'municipioNascimento', 'paisEstrangeiro', 'escola', 'estadoCivil', 'pessoaConjuge', 'ocupacao', 'refCodReligiao', 'inputFilter', 'id', 'nome', 'dataCad', 'url', 'tipo', 'dataRev', 'email', 'situacao', 'origemGravacao', 'operacao', 'idsisRev', 'idsisCad', 'pessoaCad', 'pessoaRev', 'usuario', 'oldId');
        }

        return array('__isInitialized__', 'dataNasc', 'sexo', 'dataUniao', 'dataObito', 'nacionalidade', 'dataChegadaBrasil', 'ultimaEmpresa', 'nomeMae', 'nomePai', 'nomeConjuge', 'nomeResponsavel', 'justificativaProvisorio', 'refCodSistema', 'cpf', 'pessoaMae', 'pessoaPai', 'pessoaResponsavel', 'municipioNascimento', 'paisEstrangeiro', 'escola', 'estadoCivil', 'pessoaConjuge', 'ocupacao', 'refCodReligiao', 'inputFilter', 'id', 'nome', 'dataCad', 'url', 'tipo', 'dataRev', 'email', 'situacao', 'origemGravacao', 'operacao', 'idsisRev', 'idsisCad', 'pessoaCad', 'pessoaRev', 'usuario', 'oldId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Fisica $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function checkSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkSexo', array());

        return parent::checkSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function checkNacionalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkNacionalidade', array());

        return parent::checkNacionalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataNasc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataNasc', array());

        return parent::getDataNasc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataNasc($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataNasc', array($value));

        return parent::setDataNasc($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', array());

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', array($value));

        return parent::setSexo($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataUniao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataUniao', array());

        return parent::getDataUniao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataUniao($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataUniao', array($value));

        return parent::setDataUniao($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataObito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataObito', array());

        return parent::getDataObito();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataObito($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataObito', array($value));

        return parent::setDataObito($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getNacionalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNacionalidade', array());

        return parent::getNacionalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setNacionalidade($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNacionalidade', array($value));

        return parent::setNacionalidade($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataChegadaBrasil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataChegadaBrasil', array());

        return parent::getDataChegadaBrasil();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataChegadaBrasil($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataChegadaBrasil', array($value));

        return parent::setDataChegadaBrasil($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getUltimaEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUltimaEmpresa', array());

        return parent::getUltimaEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setUltimaEmpresa($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUltimaEmpresa', array($value));

        return parent::setUltimaEmpresa($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeMae()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeMae', array());

        return parent::getNomeMae();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeMae($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeMae', array($value));

        return parent::setNomeMae($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomePai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomePai', array());

        return parent::getNomePai();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomePai($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomePai', array($value));

        return parent::setNomePai($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeConjuge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeConjuge', array());

        return parent::getNomeConjuge();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeConjuge($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeConjuge', array($value));

        return parent::setNomeConjuge($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeResponsavel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeResponsavel', array());

        return parent::getNomeResponsavel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeResponsavel($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeResponsavel', array($value));

        return parent::setNomeResponsavel($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getJustificativaProvisorio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJustificativaProvisorio', array());

        return parent::getJustificativaProvisorio();
    }

    /**
     * {@inheritDoc}
     */
    public function setJustificativaProvisorio($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJustificativaProvisorio', array($value));

        return parent::setJustificativaProvisorio($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataRev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataRev', array());

        return parent::getDataRev();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataRev($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataRev', array($value));

        return parent::setDataRev($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCad', array());

        return parent::getDataCad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCad($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCad', array($value));

        return parent::setDataCad($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperacao', array());

        return parent::getOperacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperacao($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperacao', array($value));

        return parent::setOperacao($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsisRev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsisRev', array());

        return parent::getIdsisRev();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsisRev($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsisRev', array($value));

        return parent::setIdsisRev($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsisCad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsisCad', array());

        return parent::getIdsisCad();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsisCad($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsisCad', array($value));

        return parent::setIdsisCad($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefCodSistema()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefCodSistema', array());

        return parent::getRefCodSistema();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefCodSistema($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefCodSistema', array($value));

        return parent::setRefCodSistema($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpf', array());

        return parent::getCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpf($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpf', array($value));

        return parent::setCpf($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpesMae()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpesMae', array());

        return parent::getIdpesMae();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpesMae($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpesMae', array($value));

        return parent::setIdpesMae($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpesPai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpesPai', array());

        return parent::getIdpesPai();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpesPai($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpesPai', array($value));

        return parent::setIdpesPai($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpesResponsavel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpesResponsavel', array());

        return parent::getIdpesResponsavel();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpesResponsavel($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpesResponsavel', array($value));

        return parent::setIdpesResponsavel($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmunNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmunNascimento', array());

        return parent::getIdmunNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmunNascimento($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmunNascimento', array($value));

        return parent::setIdmunNascimento($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpaisEstrangeiro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpaisEstrangeiro', array());

        return parent::getIdpaisEstrangeiro();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpaisEstrangeiro($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpaisEstrangeiro', array($value));

        return parent::setIdpaisEstrangeiro($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdesco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdesco', array());

        return parent::getIdesco();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdesco($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdesco', array($value));

        return parent::setIdesco($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdeciv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdeciv', array());

        return parent::getIdeciv();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdeciv($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdeciv', array($value));

        return parent::setIdeciv($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpesCon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpesCon', array());

        return parent::getIdpesCon();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpesCon($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpesCon', array($value));

        return parent::setIdpesCon($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdocup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdocup', array());

        return parent::getIdocup();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdocup($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdocup', array($value));

        return parent::setIdocup($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpesRev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpesRev', array());

        return parent::getIdpesRev();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpesRev($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpesRev', array($value));

        return parent::setIdpesRev($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpesCad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpesCad', array());

        return parent::getIdpesCad();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpesCad($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpesCad', array($value));

        return parent::setIdpesCad($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefCodReligiao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefCodReligiao', array());

        return parent::getRefCodReligiao();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefCodReligiao($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefCodReligiao', array($value));

        return parent::setRefCodReligiao($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data));

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubscribedEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubscribedEvents', array());

        return parent::getSubscribedEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function timestamp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'timestamp', array());

        return parent::timestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function checkOperacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkOperacao', array());

        return parent::checkOperacao();
    }

    /**
     * {@inheritDoc}
     */
    public function checkOrigemGravacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkOrigemGravacao', array());

        return parent::checkOrigemGravacao();
    }

    /**
     * {@inheritDoc}
     */
    public function checkTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkTipo', array());

        return parent::checkTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function checkSituacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkSituacao', array());

        return parent::checkSituacao();
    }

    /**
     * {@inheritDoc}
     */
    public function onFlush(\Doctrine\ORM\Event\OnFlushEventArgs $args)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onFlush', array($args));

        return parent::onFlush($args);
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate(\Doctrine\ORM\Event\PreUpdateEventArgs $args)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', array($args));

        return parent::preUpdate($args);
    }

    /**
     * {@inheritDoc}
     */
    public function postFlush(\Doctrine\ORM\Event\PostFlushEventArgs $args)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'postFlush', array($args));

        return parent::postFlush($args);
    }

    /**
     * {@inheritDoc}
     */
    public function populate($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($data));

        return parent::populate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($value));

        return parent::setId($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($value));

        return parent::setNome($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($value));

        return parent::setTipo($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($value));

        return parent::setEmail($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituacao', array());

        return parent::getSituacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituacao($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituacao', array($value));

        return parent::setSituacao($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigemGravacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigemGravacao', array());

        return parent::getOrigemGravacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigemGravacao($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigemGravacao', array($value));

        return parent::setOrigemGravacao($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoaCad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoaCad', array());

        return parent::getPessoaCad();
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoaCad($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoaCad', array($value));

        return parent::setPessoaCad($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoaRev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoaRev', array());

        return parent::getPessoaRev();
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoaRev($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoaRev', array($value));

        return parent::setPessoaRev($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getFisica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFisica', array());

        return parent::getFisica();
    }

    /**
     * {@inheritDoc}
     */
    public function setFisica($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFisica', array($value));

        return parent::setFisica($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', array());

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function removeInputFilter($input)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInputFilter', array($input));

        return parent::removeInputFilter($input);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
