<?php

namespace DoctrineORMModule\Proxy\__CG__\Portal\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Funcionario extends \Portal\Entity\Funcionario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'refCodPessoaFj', 'matricula', 'senha', 'ativo', 'refSec', 'ramal', 'sequencial', 'opcaoMenu', 'refCodSetor', 'refCodFuncionarioVinculo', 'tempoExpiraSenha', 'tempoExpiraConta', 'dataTrocaSenha', 'dataReativaConta', 'refRefCodPessoaFj', 'proibido', 'refCodSetorNew', 'matriculaNew', 'matriculaPermanente', 'tipoMenu', 'ipLogado', 'dataLogin', 'email', 'statusToken', 'inputFilter');
        }

        return array('__isInitialized__', 'id', 'refCodPessoaFj', 'matricula', 'senha', 'ativo', 'refSec', 'ramal', 'sequencial', 'opcaoMenu', 'refCodSetor', 'refCodFuncionarioVinculo', 'tempoExpiraSenha', 'tempoExpiraConta', 'dataTrocaSenha', 'dataReativaConta', 'refRefCodPessoaFj', 'proibido', 'refCodSetorNew', 'matriculaNew', 'matriculaPermanente', 'tipoMenu', 'ipLogado', 'dataLogin', 'email', 'statusToken', 'inputFilter');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Funcionario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data));

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($value));

        return parent::setId($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefCodPessoaFj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefCodPessoaFj', array());

        return parent::getRefCodPessoaFj();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefCodPessoaFj($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefCodPessoaFj', array($value));

        return parent::setRefCodPessoaFj($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricula', array());

        return parent::getMatricula();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricula($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricula', array($value));

        return parent::setMatricula($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($value));

        return parent::setSenha($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', array());

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($value));

        return parent::setAtivo($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefSec()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefSec', array());

        return parent::getRefSec();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefSec($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefSec', array($value));

        return parent::setRefSec($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRamal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRamal', array());

        return parent::getRamal();
    }

    /**
     * {@inheritDoc}
     */
    public function setRamal($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRamal', array($value));

        return parent::setRamal($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSequencial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSequencial', array());

        return parent::getSequencial();
    }

    /**
     * {@inheritDoc}
     */
    public function setSequencial($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSequencial', array($value));

        return parent::setSequencial($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpcaoMenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpcaoMenu', array());

        return parent::getOpcaoMenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpcaoMenu($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpcaoMenu', array($value));

        return parent::setOpcaoMenu($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefCodSetor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefCodSetor', array());

        return parent::getRefCodSetor();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefCodSetor($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefCodSetor', array($value));

        return parent::setRefCodSetor($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefCodFuncionarioVinculo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefCodFuncionarioVinculo', array());

        return parent::getRefCodFuncionarioVinculo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefCodFuncionarioVinculo($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefCodFuncionarioVinculo', array($value));

        return parent::setRefCodFuncionarioVinculo($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempoExpiraSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempoExpiraSenha', array());

        return parent::getTempoExpiraSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempoExpiraSenha($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempoExpiraSenha', array($value));

        return parent::setTempoExpiraSenha($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempoExpiraConta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempoExpiraConta', array());

        return parent::getTempoExpiraConta();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempoExpiraConta($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempoExpiraConta', array($value));

        return parent::setTempoExpiraConta($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataTrocaSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataTrocaSenha', array());

        return parent::getDataTrocaSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataTrocaSenha($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataTrocaSenha', array($value));

        return parent::setDataTrocaSenha($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataReativaConta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataReativaConta', array());

        return parent::getDataReativaConta();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataReativaConta($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataReativaConta', array($value));

        return parent::setDataReativaConta($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefRefCodPessoaFj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefRefCodPessoaFj', array());

        return parent::getRefRefCodPessoaFj();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefRefCodPessoaFj($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefRefCodPessoaFj', array($value));

        return parent::setRefRefCodPessoaFj($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getProibido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProibido', array());

        return parent::getProibido();
    }

    /**
     * {@inheritDoc}
     */
    public function setProibido($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProibido', array($value));

        return parent::setProibido($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefCodSetorNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefCodSetorNew', array());

        return parent::getRefCodSetorNew();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefCodSetorNew($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefCodSetorNew', array($value));

        return parent::setRefCodSetorNew($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculaNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculaNew', array());

        return parent::getMatriculaNew();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculaNew($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculaNew', array($value));

        return parent::setMatriculaNew($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculaPermanente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculaPermanente', array());

        return parent::getMatriculaPermanente();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculaPermanente($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculaPermanente', array($value));

        return parent::setMatriculaPermanente($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoMenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoMenu', array());

        return parent::getTipoMenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoMenu($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoMenu', array($value));

        return parent::setTipoMenu($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getIpLogado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIpLogado', array());

        return parent::getIpLogado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIpLogado($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIpLogado', array($value));

        return parent::setIpLogado($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataLogin', array());

        return parent::getDataLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataLogin($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataLogin', array($value));

        return parent::setDataLogin($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($value));

        return parent::setEmail($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', array());

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function removeInputFilter($input)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInputFilter', array($input));

        return parent::removeInputFilter($input);
    }

}
