<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Escola\Module'                     => __DIR__ . '/Module.php',
    'Escola\Controller\IndexController' => __DIR__ . '/src/Escola/Controller/IndexController.php',
);
