<div class="container">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="/">Ínicio</a></li>
            <li><a href="/usuario/fisica">Cadastro de Pessoa Física</a></li>
            <li class="active">Salvar</li>
        </ol>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h1><i class="icon icon-group"></i> Cadastro <small>de pessoa física</small></h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>Salvar</b>
                </div>

                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                            $this->form->prepare();
                            //echo $this->form($form);
                            echo $this->form()->openTag($form);
                            $usersandbox = $this->form->get('usersandbox');
                            $id = $usersandbox->get('id');
                            $nome = $usersandbox->get('nome');

                            $documentosandbox = $usersandbox->get('documentosandbox');
                            $iddocumento = $documentosandbox->get('id');
                            $nomedocumento = $documentosandbox->get('nome');
                            $tipoLogradouro = $documentosandbox->get('tipoLogradouro');

                            echo $this->formInput($id);
                            echo $this->formInput($iddocumento);
                            ?>
                            <br>

                            <div class="form-group required">
                                <label for="nome">
                                    <?php
                                    echo $nome->getOption('label');
                                    ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-6">
                                        <?php
                                        echo $this->formInput($nome);
                                        ?>
                                        <span class="help-block">
                                                <?php
                                                echo $this->formElementErrors($nome);
                                                ?>
                                            </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group required">
                                <label for="nome">
                                    <?php
                                    echo $nomedocumento->getOption('label');
                                    ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-6">
                                        <?php
                                        echo $this->formInput($nomedocumento);
                                        ?>
                                        <span class="help-block">
                                                <?php
                                                echo $this->formElementErrors($nomedocumento);
                                                ?>
                                            </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group required">
                                <label for="nome">
                                    <?php
                                    echo $tipoLogradouro->getOption('label');
                                    ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-6">
                                        <?php
                                        echo $this->formSelect($tipoLogradouro);
                                        ?>
                                        <span class="help-block">
                                                <?php
                                                echo $this->formElementErrors($tipoLogradouro);
                                                ?>
                                            </span>
                                    </div>
                                </div>
                            </div>

                            <br>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        $enviar = $this->form->get('submit');
                                        echo $this->formElement($enviar);
                                        ?>
                                    </div>
                                </div>
                            </div>



                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<?php
echo $this->headLink()->prependStylesheet($this->basePath() . '/componentes/chosen/chosen.css');
echo $this->headScript()->prependFile($this->basePath() . '/componentes/chosen/chosen.jquery.min.js', 'text/javascript');
echo $this->headScript()->prependFile($this->basePath()
    . '/componentes/jquery.masked-input/jquery.maskedinput.min.js');
?>
<script type="text/javascript">
    var config = {
        '.chosen-select'           : {},
        '.chosen-select-deselect'  : {allow_single_deselect:true},
        '.chosen-select-no-single' : {disable_search_threshold:10},
        '.chosen-select-no-results': {no_results_text:'Oops, nada foi encontrado!'},
        '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
        $(selector).chosen(config[selector]);
    }
    $(document).ready(function() {

    });
</script>