<?php
$this->inlineScript()->appendFile('/js/anoletivo.js')
                     ->appendFile('/componentes/moment/min/moment.min.js')
                     ->appendFile('/componentes/moment/locale/pt-br.js')
                     ->appendFile('/componentes/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js');
?>
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="/">Ínicio</a></li>
            <li><a href="/escola/ano-letivo">Cadastro de Ano Letivo</a></li>
            <li class="active">Salvar</li>
        </ol>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h1><i class="icon icon-calendar"></i> Cadastro <small>de ano letivo</small></h1>
            </div>
        </div>
    </div>
</div>

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>Salvar</b>
                </div>

                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                            $this->form->prepare();
                            echo $this->form()->openTag($form);
                            $id = $this->form->get('id');
                            $ano = $this->form->get('ano');
                            $escola = $this->form->get('escola');
                            $anoLetivoModulos = $this->form->get('anoLetivoModulos');
                            echo $this->formInput($id);
                            echo $this->formInput($escola);
                            ?>
                            <br>

                            <div class="form-group required">
                                <label for="ano">
                                    <?php
                                    echo $ano->getOption('label');
                                    ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-2">
                                        <?php
                                        echo $this->formSelect($ano);
                                        ?>
                                        <span class="help-block">
                                                <?php
                                                echo $this->formElementErrors($ano);
                                                ?>
                                            </span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-11">
                                    <div class="panel panel-primary">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                Módulos
                                            </h4>
                                        </div>
                                        <div class="panel-body">

                                            <?php
                                            //echo $this->formCollection($anoLetivoModulos);
                                            $estilos = array('bg-default', 'bg-warning');
                                            $this->cycle()->assign($estilos);
                                            foreach ($anoLetivoModulos as $anoLetivoModulo):
                                                echo $this->formInput($anoLetivoModulo->get('id'));
                                                $modulo = $anoLetivoModulo->get('modulo');
                                                $dataInicio = $anoLetivoModulo->get('dataInicio');
                                                $dataFim = $anoLetivoModulo->get('dataFim');
                                                //echo $this->formInput($anoLetivoModulo->get('anoLetivo'));
                                                ?>
                                                <div class="row <?php echo $this->cycle()->next();?> anoLetivoModulos">
                                                    <div class="form-group">
                                                        <div class="col-md-1">
                                                            <label
                                                                for="<?php
                                                                echo $anoLetivoModulo->get('modulo')->getOption('label');
                                                                ?>"><?php
                                                                echo $anoLetivoModulo->get('modulo')->getOption('label'); ?>
                                                            </label>
                                                        </div>
                                                        <div class="col-md-3">
                                                            <?php echo $this->formSelect($anoLetivoModulo->get('modulo'));?>
                                                        </div>
                                                        <div class="col-md-1">
                                                            <label
                                                                for="<?php
                                                                echo $anoLetivoModulo->get('dataInicio')->getOption('label');
                                                                ?>"><?php
                                                                echo $anoLetivoModulo->get('dataInicio')->getOption('label'); ?>
                                                            </label>
                                                        </div>
                                                        <div class="col-md-2">
                                                            <div class="input-group date">
                                                                <?php echo $this->formInput($anoLetivoModulo->get('dataInicio'));?>
                                                                <span class="input-group-addon">
                                                                    <span class="glyphicon glyphicon-calendar"></span>
                                                                </span>
                                                            </div>
                                                            <span class="help-block">
                                                                <?php
                                                                //var_dump($dataInicio);
                                                                echo $this->formElementErrors($dataInicio, array('class' => 'inline'));
                                                                echo $this->formElementErrors($anoLetivoModulo->get('dataInicio'));
                                                                ?>
                                                            </span>
                                                        </div>
                                                        <div class="col-md-1">
                                                            <label for="<?php
                                                            echo $anoLetivoModulo->get('dataFim')->getOption('label'); ?>"><?php
                                                                echo $anoLetivoModulo->get('dataFim')->getOption('label'); ?></label>
                                                        </div>
                                                        <div class="col-md-2">
                                                            <div class="input-group date">
                                                                <?php echo $this->formInput($anoLetivoModulo->get('dataFim'));?>
                                                                <span class="input-group-addon"><span
                                                                        class="glyphicon glyphicon-calendar"></span></span>
                                                            </div>
                                                            <span class="help-block">
                                                                <?php
                                                                echo $this->formElementErrors($anoLetivoModulo->get('dataFim'));
                                                                ?>
                                                            </span>
                                                        </div>
                                                    </div>

                                                </div>
                                                <?php
                                            endforeach;
                                            ?>

                                        </div>
                                        <div class="panel-footer">
                                            <button type="button" class="btn btn-info btn-inserir-modulo">
                                                <i class="icon icon-plus"></i> Inserir novo módulo
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <br>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        $enviar = $this->form->get('submit');
                                        echo $this->formElement($enviar);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->headLink()->prependStylesheet($this->basePath()
    . "/componentes/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css") ?>

<script type="text/javascript">
    $(function () {
        $('.dataInicio, .dataFim').datetimepicker({
            locale: 'pt-br',
            format: 'DD-MM-YYYY'
        });
    })
</script>
