<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Drh\Module'                           => __DIR__ . '/Module.php',
    'Drh\Controller\FuncionarioController' => __DIR__ . '/src/Drh/Controller/FuncionarioController.php',
    'Drh\Controller\IndexController'       => __DIR__ . '/src/Drh/Controller/IndexController.php',
    'Drh\Controller\SetorController'       => __DIR__ . '/src/Drh/Controller/SetorController.php',
    'Drh\Entity\Funcionario'               => __DIR__ . '/src/Drh/Entity/Funcionario.php',
    'Drh\Entity\Setor'                     => __DIR__ . '/src/Drh/Entity/Setor.php',
    'Drh\Fixture\FuncionarioLoad'          => __DIR__ . '/src/Drh/Fixture/FuncionarioLoad.php',
    'Drh\Fixture\SetorLoad'                => __DIR__ . '/src/Drh/Fixture/SetorLoad.php',
    'Drh\Form\Funcionario'                 => __DIR__ . '/src/Drh/Form/Funcionario.php',
    'Drh\Form\Setor'                       => __DIR__ . '/src/Drh/Form/Setor.php',
    'DrhTest\Bootstrap'                    => __DIR__ . '/tests/Bootstrap.php',
    'FuncionarioControllerTest'            => __DIR__ . '/tests/src/Drh/Controller/FuncionarioControllerTest.php',
    'SetorControllerTest'                  => __DIR__ . '/tests/src/Drh/Controller/SetorControllerTest.php',
    'Drh\Entity\FuncionarioTest'           => __DIR__ . '/tests/src/Drh/Entity/FuncionarioTest.php',
    'Drh\Entity\SetorTest'                 => __DIR__ . '/tests/src/Drh/Entity/SetorTest.php',
);
