<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'drh/funcionario/busca'    => __DIR__ . '/view/drh/funcionario/busca.phtml',
    'drh/funcionario/detalhes' => __DIR__ . '/view/drh/funcionario/detalhes.phtml',
    'drh/funcionario/index'    => __DIR__ . '/view/drh/funcionario/index.phtml',
    'drh/funcionario/save'     => __DIR__ . '/view/drh/funcionario/save.phtml',
    'drh/index/index'          => __DIR__ . '/view/drh/index/index.phtml',
    'drh/setor/busca'          => __DIR__ . '/view/drh/setor/busca.phtml',
    'drh/setor/detalhes'       => __DIR__ . '/view/drh/setor/detalhes.phtml',
    'drh/setor/index'          => __DIR__ . '/view/drh/setor/index.phtml',
    'drh/setor/save'           => __DIR__ . '/view/drh/setor/save.phtml',
);
