<div class="row">
	<ol class="breadcrumb">
		<li><a href="/">Ínicio</a></li>
	  	<li><a href="#">Configurações</a></li>
	  	<li class="active">Permissões</li>
	</ol>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
  			<h1><i class="icon icon-lock"></i> Permissões <small>de usuários</small></h1>
		</div>
	</div>	
</div>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
  			<div class="panel-heading">
  				<b>Lista de Permissões</b>
  			</div>
  			<div class="row">
				<div class="col-md-4 p-20">
					<a href="/auth/role/save" class="btn btn-primary"><i class="icon icon-plus"></i> Nova Permissão</a>
				</div>
				<div class="col-md-4 col-md-offset-4 p-20">
					<form action="">
						<div class="input-group">
		  					<span class="input-group-addon"><i class="icon icon-search"></i></span>
		  					<input type="text" class="form-control" placeholder="Pesquisar">
						</div>
					</form>
				</div>
			</div>			
			<div class="row">			
				<div class="col-md-12 p-20">
					<table class="table table-bordered table-hover"> 
	  				<thead>
			  			<tr>
			  				<th width="5%">#</th>
			  				<th>Funcionário</th>
			  				<th>Recurso</th>
			  				<th>Privilégio</th>
			  				<th width="30%">AÇÕES</th>
			  			</tr> 
	  				</thead>
	  				<tbody>
	  					<?php						
						if (count($this->dados) > 0):
							foreach ($this->dados as $role):
	  					?>
					  			<tr>
					  				<td>
					  					<?php 
					  					
					  						echo $role->getId();
					  					?>				
					  				</td>
					  				<td>
					  					<?php
					  					echo $role->getFuncionario()->getNome();
					  					?>
					  				</td>
					  				<td>
					  					<?php
					  					echo $role->getResource()->getNome();
					  					?>
					  				</td>
					  				<td>
					  					<span class="label label-<?php
						  					echo ($role->getPrivilegio() == 0) ? "success" : "danger";					  						
						  					?>">
						  					<?php
						  					echo ($role->getPrivilegio() == 0) ? "Permitir" : "Negado";					  						
						  					?>
					  					</span>
					  				</td>
					  				<td>
					  					<a href="/auth/role/ver/id/<?php echo $role->getId()?>" class="btn btn-info"><i class="icon icon-list"></i> Ver detalhes</a>
					  					<a href="/auth/role/save/id/<?php echo $role->getId()?>" class="btn btn-primary"><i class="icon icon-pencil"></i> Editar</a>
					  					<a href="/auth/role/delete/id/<?php echo $role->getId()?>" class="btn btn-danger"><i class="icon icon-trash"></i> Apagar</a>
					  				</td>
					  			</tr>
				  		<?php
				  			endforeach;
				  		else:
				  		?>
				  			<tr class="warning">
				  				<td colspan="3" class="text-center">
				  					<b>Nenhum registro encontrado</b>
				  				</td>
				  			</tr>
				  		<?php
				  		endif;
				  		?>
		  			</tbody>
	  				</table>
	    		</div>
			</div>
			<div class="row">
				<div class="col-md-4 col-md-offset-4">
					<ul class="pagination">
					    <li class="disabled"><a href="#">«</a></li>
					    <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
					    <li><a href="#">2</a></li>
					    <li><a href="#">3</a></li>
					    <li><a href="#">4</a></li>
					    <li><a href="#">5</a></li>
					    <li><a href="#">»</a></li>
				   	</ul>
				</div>
			</div>  			
		</div>
	</div>
</div>
