<?php
/**
 * Created by PhpStorm.
 * User: eduardojunior
 * Date: 22/09/16
 * Time: 10:41
 */
namespace Api\Controller;

use Core\Controller\RestController;
use Usuario\Entity\Pessoa;
use Zend\View\Model\JsonModel;
use Doctrine\ORM\AbstractQuery;

class PessoaController extends RestController
{
    public function getList()
    {
        //$results = $this->getEntityManager()->getRepository('Usuario\Entity\Pessoa')->findAll();
        $queryBuilder = $this->getEntityManager()->createQuery("SELECT p FROM Usuario\Entity\Pessoa p");
        $data = $queryBuilder->getResult(AbstractQuery::HYDRATE_ARRAY);

//        $data = array();
//        foreach ($results as $result){
//            $data[] = [
//                'id' => $result->getId(),
//                'nome' => $result->getNome(),
//                'dataCad' => $result->getDataCad(),
//                'url' => $result->getUrl(),
//                'email' => $result->getEmail(),
//                'situacao' => $result->getSituacao(),
//                'enderecoExterno' => $result->getEnderecoExterno(),
//                'telefones' => $result->getTelefones()
//            ];
//        }
        //ripler em busca da perfeicao

        return new JsonModel(array('data' => $data));
    }

    public function get($id)
    {
        return parent::get($id); // TODO: Change the autogenerated stub
    }

    public function create($data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function update($id, $data)
    {

    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}