<div class="row">
    <ol class="breadcrumb">
        <li><a href="/">Ínicio</a></li>
        <li><a href="/escola">Escola</a></li>
        <li class="active">Cadastro de Escola</li>
    </ol>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="page-header">
            <h1><i class="icon icon-home"></i> Cadastro <small>de escola</small></h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <b>Lista de Escolas</b>
            </div>
            <div class="row">
                <div class="col-md-4 p-20">
                    <a href="/escola/escola/save" class="btn btn-primary">
                        <i class="icon icon-plus"></i> Nova Escola
                    </a>
                </div>
                <div class="col-md-4 col-md-offset-4 p-20">
                    <form id="busca" method="post" action="/escola/escola/busca">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="icon icon-search"></i></span>
                            <input type="text" class="form-control" name="q" placeholder="Pesquisar">
                        </div>
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 p-20">
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th width="5%">#</th>
                            <th>NOME</th>
<!--                            <th width="10%">REDE DE ENSINO</th>-->
                            <th width="40%">ANOS LETIVOS</th>
                            <th width="30%">AÇÕES</th>
                        </tr>
                        </thead>
                        <tbody class="dados">
                        <?php
                        if (count($this->dados) > 0):
                            $estilos = array('active','warning');
                            $this->cycle()->assign($estilos);
                            foreach ($this->dados as $escola):
                                ?>
                                <tr class="<?php echo $this->cycle()->next();?>">
                                    <td>
                                        <?php
                                        echo $escola->getId();
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                        echo $escola->getJuridica()->getNome();
                                        ?> (<?php echo $escola->getRedeEnsino()->getNome();?>)
                                    </td>
<!--                                    <td>-->
<!--                                        --><?php //echo $escola->getRedeEnsino()->getNome();?>
<!--                                    </td>-->
                                    <td>
                                        <?php
                                        if ($escola->getAnosLetivos()->count() > 0):
                                        ?>
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th>ANO</th>
                                                        <th>AÇÕES</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                <?php
                                                foreach ($escola->getAnosLetivos() as $anoLetivo):
                                                ?>
                                                    <tr>
                                                        <td><?php echo $anoLetivo->getAno();?></td>
                                                        <td>
                                                            <?php if ($anoLetivo->getAndamento() == 2):
                                                            ?>
                                                                <i class="glyphicon glyphicon-ok"></i> <br>
                                                                Ano Finalizado
                                                                <?php
                                                            else:
                                                                //@TODO Arquivo que inicializa o ano letivo : educar_iniciar_ano_letivo.php
                                                            ?>
                                                                <a href="<?php echo $this->url('escola/default',
                                                                    array(
                                                                        'controller' => 'anoLetivo',
                                                                        'action' => 'andamento'
                                                                    ), true);?>/id/<?php echo $anoLetivo->getId();?>/status/iniciar"
                                                                   class="btn btn-success btn-sm"
                                                                <?php if ($anoLetivo->getAndamento() == 1):?>disabled="disabled"
                                                                <?php endif ?>>
                                                                    <i class="glyphicon glyphicon-play"></i>
                                                                     INICIAR
                                                                </a>
                                                                <a href="<?php echo $this->url('escola/default', array(
                                                                    'controller' => 'anoLetivo',
                                                                    'action' => 'andamento'
                                                                ), true);?>/id/<?php echo $anoLetivo->getId();?>/status/finalizar"
                                                                   class="btn btn-danger btn-sm"
                                                                <?php if ($anoLetivo->getAndamento() == 0): ?>disabled="disabled"
                                                                    <?php endif ?>>
                                                                    <i class="glyphicon glyphicon-stop"></i>
                                                                     FINALIZAR</a>
                                                                <a href="<?php echo $this->url('escola/default', array('controller'=> 'anoletivo', 'action' => 'save'), true); ?>/escola/<?php echo $escola->getId();?>/id/<?php echo $anoLetivo->getId();?>" class="btn btn-primary btn-sm">
                                                                    <i class="icon icon-pencil"></i> EDITAR</a>
                                                                <a href="<?php echo $this->url('escola/default', array(
                                                                    'controller' => 'anoLetivo',
                                                                    'action' => 'delete'
                                                                ), true);?>/id/<?php echo $anoLetivo->getId();?>"
                                                                   class="btn btn-danger delete btn-sm">
                                                                    <i class="icon icon-trash"></i> APAGAR</a>

                                                            <?php endif ?>
                                                        </td>
                                                    </tr>
                                                <?php
                                                endforeach;
                                                ?>
                                                </tbody>
                                            </table>
                                        <?php
                                        endif;
                                        ?>
                                        <a href="/escola/ano-letivo/save/escola/<?php echo $escola->getId();?>"
                                           class="btn btn-info"><i class="icon icon-cog"></i> Definir ano letivo</a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('escola', array('controller' => 'anoletivo',
                                            'action' => 'index', 'escola' => $escola->getId()));?>"
                                           class="btn btn-info btn-detalhes" data-toggle="modal"
                                           data-target="#detalhesModal"><i class="icon icon-list"></i> Ver detalhes</a>
                                        <a href="/escola/escola/save/id/<?php echo $escola->getId()?>"
                                           class="btn btn-primary"><i class="icon icon-pencil"></i> Editar</a>
                                        <a href="/escola/escola/delete/id/<?php echo $escola->getId()?>"
                                           class="btn btn-danger delete"><i class="icon icon-trash"></i> Apagar</a>
                                    </td>
                                </tr>
                                <?php
                            endforeach;
                        else:
                            ?>
                            <tr class="warning">
                                <td colspan="4" class="text-center">
                                    <b>Nenhum registro encontrado</b>
                                </td>
                            </tr>
                            <?php
                        endif;
                        ?>
                        </tbody>
                        <tr class="loading">
                            <td class="info text-center" colspan="4">
                                <i class='glyphicon icon-spinner icon-spin icon-large'></i> Carregando...
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <?php
                    echo $this->paginationControl($dados, 'Sliding', 'partials/paginator/control.phtml');
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Apagar?</h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger">
                    <p>Tem certeza que deseja remover esse registro?</p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
                <button type="button" class="btn btn-primary confirmation">Sim</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="detalhesModal" tabindex="-1" role="dialog" aria-labelledby="detalhesModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" area-hidden="true">&times;</button>
                <h4 class="modal-title" id="detalhesModalLabel">Detalhes</h4>
            </div>

            <div class="modal-body">
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>

        </div>
    </div>

</div>

<script type="text/javascript">
    $(document).ready(function() {
        url = null;
        $('.dados').on("click", ".delete", function(event){
            event.preventDefault();
            url = $(this).attr('href');
            $("#deleteModal").modal();
        });

        $('.dados').on('click', '.btn-detalhes', function(event){
            event.preventDefault();
            var id = $(this).attr('href').split('#')[1];
            $.ajax({
                type: "GET",
                url: '/escola/escola/detalhes/id/' + id,
                success: function(data){
                    $('#detalhesModalLabel').html('Detalhes Escola ID#' + id);
                    $('#detalhesModal .modal-body').html(data);
                },
                beforeSend: function(){
                    $('#detalhesModalLabel').html('Detalhes');
                    $('#detalhesModal .modal-body').html("<p class='text-center'> <i class='glyphicon icon-spinner icon-spin icon-large'></i> Carregando...</p>");
                }
            });
            //$('#detalhesModal').modal();
        });

        $(".confirmation").click(function(event){
            $("#deleteModal").modal('hide');
            window.location.href = url;
        });
        $( "#busca" ).submit(function( event ) {
            event.preventDefault();
            // var query = $(this).serialize();
            var query = $("input[name=q]").val();
            $.ajax({
                type : "POST",
                data : { q:query },
                url : $(this).attr('action'),
                success : function(result){
                    $(".dados").html(result);
                },
                beforeSend : function(){
                    $(".dados").html('');
                    $(".dados").hide();
                    $(".loading").show();
                },
                complete : function(msg){
                    $(".loading").hide();
                    $(".dados").show();
                }
            })
        });

        $("#go").click(function(event) {
            $("#busca").submit();
        });
    });
</script>
