<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
//    'error/404'               => __DIR__ . '/view/error/404.phtml',
//    'error/index'             => __DIR__ . '/view/error/index.phtml',
//    'layout/layout'           => __DIR__ . '/view/layout/layout.phtml',
    'usuario/fisica/busca'    => __DIR__ . '/view/usuario/fisica/busca.phtml',
    'usuario/fisica/index'    => __DIR__ . '/view/usuario/fisica/index.phtml',
    'usuario/fisica/save'     => __DIR__ . '/view/usuario/fisica/save.phtml',
    'usuario/fisica/save_zf2' => __DIR__ . '/view/usuario/fisica/save_zf2.phtml',
    'usuario/index/index'     => __DIR__ . '/view/usuario/index/index.phtml',
    'usuario/pessoa/index'    => __DIR__ . '/view/usuario/pessoa/index.phtml',
    'usuario/pessoa/save'     => __DIR__ . '/view/usuario/pessoa/save.phtml',
    'usuario/raca/busca'      => __DIR__ . '/view/usuario/raca/busca.phtml',
    'usuario/raca/index'      => __DIR__ . '/view/usuario/raca/index.phtml',
    'usuario/raca/save'       => __DIR__ . '/view/usuario/raca/save.phtml',
);
