<?php						
if (count($this->dados) > 0):
	foreach ($this->dados as $resource):
	?>
			<tr>
				<td>
					<?php 
					
						echo $resource->getId();
					?>				
				</td>
				<td>
					<?php
					echo $resource->getNome();
					?>
				</td>					  									  				
				<td>
					<a href="/auth/resource/ver/id/<?php echo $resource->getId()?>" class="btn btn-info"><i class="icon icon-list"></i> Ver detalhes</a>
					<a href="/auth/resource/save/id/<?php echo $resource->getId()?>" class="btn btn-primary"><i class="icon icon-pencil"></i> Editar</a>
					<a href="/auth/resource/delete/id/<?php echo $resource->getId()?>" class="btn btn-danger delete"><i class="icon icon-trash"></i> Apagar</a>
				</td>
			</tr>
	<?php
		endforeach;
else:
?>
	<tr class="warning">
		<td colspan="3" class="text-center">
			<b>Nenhum registro encontrado</b>
		</td>
	</tr>
<?php
endif;
?>