<?php						
if (count($this->dados) > 0):
	foreach ($this->dados as $fisica):
	?>
			<tr>
				<td>
					<?php 
					
						echo $fisica->getId();
					?>				
				</td>
				<td>
					<?php
					echo $fisica->getNome();
					?>
				</td>
				<td>
					<?php
					echo $fisica->getCpf();
					?>
				</td>
				<td>
					<?php
					echo $fisica->getSituacao();
					?>
				</td>	  									  				
				<td>
					<a href="/usuario/fisica/ver/id/<?php echo $fisica->getId()?>" class="btn btn-info"><i class="icon icon-list"></i> Ver detalhes</a>
					<a href="/usuario/fisica/save/id/<?php echo $fisica->getId()?>" class="btn btn-primary"><i class="icon icon-pencil"></i> Editar</a>
					<a href="/usuario/fisica/delete/id/<?php echo $fisica->getId()?>" class="btn btn-danger delete"><i class="icon icon-trash"></i> Apagar</a>
				</td>
			</tr>
	<?php
		endforeach;
else:
?>
	<tr class="warning">
		<td colspan="5" class="text-center">
			<b>Nenhum registro encontrado</b>
		</td>
	</tr>
<?php
endif;
?>