<div class="container">
	<div class="row">
		<ol class="breadcrumb">
			<li><a href="/">Ínicio</a></li>
		  	<li><a href="/usuario/fisica">Cadastro de Pessoa Física</a></li>
		  	<li class="active">Salvar</li>
		</ol>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
	  			<h1><i class="icon icon-group"></i> Cadastro <small>de pessoa física</small></h1>
			</div>
		</div>	
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
	  			<div class="panel-heading">
	  				<b>Salvar</b>
	  			</div>
	  			<div class="container">
					<div class="row">			
						<div class="col-md-12">
							<?php
							echo $this->form()->openTag($form);
							$id = $this->form->get('id');
							$nome = $this->form->get('nome');							
							$situacao = $this->form->get('situacao');
							$dataNasc = $this->form->get('dataNasc');
							$cpf = $this->form->get('cpf');
							$sexo = $this->form->get('sexo');
							$estadoCivil = $this->form->get('estadoCivil');
							$url = $this->form->get('url');
							$email = $this->form->get('email');
							$raca = $this->form->get('raca');
							$enderecoExterno = $this->form->get('enderecoExterno');
							
							// $cep = $this->form->get('cep');
							$cep = $enderecoExterno->get('cep');
							// $tipoLogradouro = $this->form->get('tipoLogradouro');
							$tipoLogradouro = $enderecoExterno->get('tipoLogradouro');
							// $logradouro = $this->form->get('logradouro');
							$logradouro = $enderecoExterno->get('logradouro');
							// $numero = $this->form->get('numero');
							$numero = $enderecoExterno->get('numero');
							// $cidade = $this->form->get('cidade');
							$cidade = $enderecoExterno->get('cidade');
							// $bairro = $this->form->get('bairro');
							$bairro = $enderecoExterno->get('bairro');
							// $uf = $this->form->get('uf');
							$uf = $enderecoExterno->get('siglaUf');
							// $letra = $this->form->get('letra');
							$letra = $enderecoExterno->get('letra');
                            // $apartamento = $this->form->get('apartamento');
                            $apartamento = $enderecoExterno->get('apartamento');
                            // $bloco = $this->form->get('bloco');
                            $bloco = $enderecoExterno->get('bloco');
                            // $andar = $this->form->get('andar');
                            $andar = $enderecoExterno->get('andar');
                            // $zonaLocalizacao = $this->form->get('zonaLocalizacao');
                            $zonaLocalizacao = $enderecoExterno->get('zonaLocalizacao');
							// $complemento = $this->form->get('complemento');
							$complemento = $enderecoExterno->get('complemento');
							$dddTelefone1 = $this->form->get('dddTelefone1');
							$telefone1 = $this->form->get('telefone1');
							$dddTelefone2 = $this->form->get('dddTelefone2');
							$telefone2 = $this->form->get('telefone2');
							$dddCelular = $this->form->get('dddCelular');
							$celular = $this->form->get('celular');
							$dddFax = $this->form->get('dddFax');
							$fax = $this->form->get('fax');
							$foto = $this->form->get('foto');
							/**
							 * @todo
							 * - Endereço 
							 * a ideia é digitar o cep, buscar na base de dados e preencher os campos de endereço de 
							 * acordo com o cep, caso nao tenha, aparecer a opção para inserção de novo cep
							 */
							echo $this->formInput($id);
							?>
							<br>
							
								<div class="form-group required">
									<label for="nome">
										<?php
										echo $nome->getOption('label');
										?>
									</label>
									<div class="row">
										<div class="col-md-6">
											<?php
											echo $this->formInput($nome);
											echo $this->formElementErrors($nome);
											?>									
										</div>
									</div>
								</div>								
								<div class="form-group">
									<label for="cpf">
										<?php
										echo $cpf->getOption('label');
										?>
									</label>
									<div class="row">
										<div class="col-md-2">
											<?php
											echo $this->formInput($cpf);
											echo $this->formElementErrors($cpf);
											?>
										</div>			
									</div>					
								</div>
								<div class="form-group">		
									<label for="dataNasc">
										<?php
										echo $dataNasc->getOption('label');
										?>
									</label>
									<div class="row">
										<div class="col-md-2">
											<?php
											echo $this->formInput($dataNasc);
											echo $this->formElementErrors($dataNasc);
											?>	
										</div>
									</div>										
								</div>
								<div class="form-group required">
									<label for="sexo">
										<?php
										echo $sexo->getOption('label');
										?>
									</label>
									<div class="row">
										<div class="col-md-2">
											<?php
											echo $this->formSelect($sexo);
											echo $this->formElementErrors($sexo);
											?>	
										</div>
									</div>										
								</div>
								<div class="form-group">
									<label for="estadoCivil">
										<?php
										echo $estadoCivil->getOption('label');
										?>
									</label>
									<div class="row">
										<div class="col-md-2">
											<?php
											echo $this->formSelect($estadoCivil);
											echo $this->formElementErrors($estadoCivil);
											?>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label for="raca">
										<?php
										echo $raca->getOption('label');
										?>
									</label>
									<div class="row">
										<div class="col-md-3">
											<?php
											echo $this->formSelect($raca);
											echo $this->formElementErrors($raca);
											?>		
										</div>
									</div>										
								</div>
								<div class="form-group">
									<label for="cep">
										<?php echo $cep->getOption('label');?>
									</label>
									<div class="row">
										<div class="col-md-1">
											<?php 
											echo $this->formInput($cep);
											echo $this->formElementErrors($cep);
											?>											
										</div>
										<div class="col-md-3 ceploading"
                                             style="padding-left:25px; padding-top:4px; display:none;">
											<i class='glyphicon icon-spinner icon-spin icon-large'></i> 
											Pesquisando CEP, aguarde!
										</div>

									</div>
								</div>
								<div class="form-group">
									<label for="tipoLogradouro">
										<?php
										echo $tipoLogradouro->getOption('label');
										?>
									</label>
									<div class="row">
										<div class="col-md-3">
											<?php
											echo $this->formSelect($tipoLogradouro);
											echo $this->formElementErrors($tipoLogradouro);
											?>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label for="logradouro">
										<?php echo $logradouro->getOption('label'); ?>
									</label>
									<div class="row">
										<div class="col-md-5">
											<?php
											echo $this->formInput($logradouro);
											echo $this->formElementErrors($logradouro);
											?>
										</div>
									</div>
								</div>

								<div class="form-group">
									<label for="numero">
										<?php echo $numero->getOption('label'); ?>
									</label>
									<div class="row">
										<div class="col-md-2">
											<?php
											echo $this->formInput($numero);
											echo $this->formElementErrors($numero);
											?>
										</div>
									</div>
								</div>

								<div class="form-group">
									<label for="complemento">
										<?php echo $complemento->getOption('label'); ?>
									</label>
									<div class="row">
										<div class="col-md-5">
											<?php
											echo $this->formInput($complemento);
											echo $this->formElementErrors($complemento);
											?>
										</div>
									</div>
								</div>

								<div class="form-group">
									<label for="letra">
										<?php echo $letra->getOption('label'); ?>
									</label>
									<div class="row">
										<div class="col-md-1">
											<?php
											echo $this->formInput($letra);
											echo $this->formElementErrors($letra);
											?>
										</div>
									</div>
								</div>

                                <div class="form-group">
                                    <label for="apartamento">
                                        <?php echo $apartamento->getOption('label');?>
                                    </label>
                                    <div class="row">
                                        <div class="col-md-1">
                                            <?php
                                            echo $this->formInput($apartamento);
                                            echo $this->formElementErrors($apartamento);
                                            ?>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                	<label for="bloco">
                                		<?php echo $bloco->getOption('label');?>
                                	</label>
                                	<div class="row">
                                		<div class="col-md-3">
                                			<?php
                                			echo $this->formInput($bloco);
                                			echo $this->formElementErrors($bloco);
                                			?>
                                		</div>
                                	</div>
                                </div>

                                <div class="form-group">
                                	<label for="andar">
                                		<?php echo $andar->getOption('label');?>
                                	</label>
                                	<div class="row">
                                		<div class="col-md-1">
                                			<?php
                                			echo $this->formInput($andar);
                                			echo $this->formElementErrors($andar);
                                			?>
                                		</div>
                                	</div>
                                </div>
								
								<div class="form-group">
									<label for="bairro">
										<?php echo $bairro->getOption('label');?>
									</label>
									<div class="row">
										<div class="col-md-5">
											<?php
											echo $this->formInput($bairro);
											echo $this->formElementErrors($bairro);
											?>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label for="zonaLocalizacao">
										<?php
										echo $zonaLocalizacao->getOption('label');
										?>
									</label>
									<div class="row">
										<div class="col-md-3">
											<?php
											echo $this->formSelect($zonaLocalizacao);
											echo $this->formElementErrors($zonaLocalizacao);
											?>		
										</div>
									</div>										
								</div>
								<div class="form-group">
									<label for="cidade">
										<?php echo $cidade->getOption('label'); ?>
									</label>
									<div class="row">
										<div class="col-md-5">
											<?php
											echo $this->formInput($cidade);
											echo $this->formElementErrors($cidade);
											?>
										</div>
									</div>
								</div>								
								
								<div class="form-group">
									<label for="uf">
										<?php
										echo $uf->getOption('label');
										?>
									</label>
									<div class="row">
										<div class="col-md-3">
											<?php
											echo $this->formSelect($uf);
											echo $this->formElementErrors($uf);
											?>		
										</div>
									</div>										
								</div>

								<div class="form-group">
									<label for="dddTelefone1">
										<?php echo $dddTelefone1->getOption('label');?>
									</label>
									<div class="row">
										<div class="col-md-1">
											<?php
											echo $this->formInput($dddTelefone1);
											echo $this->formElementErrors($dddTelefone1);
											?>
										</div>
									</div>
								</div>

								<div class="form-group">
									<label for="telefone1">
										<?php echo $telefone1->getOption('label');?>
									</label>
									<div class="row">
										<div class="col-md-2">
											<?php
											echo $this->formInput($telefone1);
											echo $this->formElementErrors($telefone1);
											?>
										</div>
									</div>
								</div>

								<div class="form-group">
									<label for="dddTelefone2">
										<?php echo $dddTelefone2->getOption('label');
										?>
									</label>
									<div class="row">
										<div class="col-md-1">
											<?php
											echo $this->formInput($dddTelefone2);
											echo $this->formElementErrors($dddTelefone2);
											?>
										</div>
									</div>
								</div>

								<div class="form-group">
									<label for="telefone2">
										<?php echo $telefone2->getOption('label');?>
									</label>
									<div class="row">
										<div class="col-md-2">
											<?php
											echo $this->formInput($telefone2);
											echo $this->formElementErrors($telefone2);
											?>
										</div>
									</div>
								</div>

								<div class="form-group">
									<label for="dddCelular">
										<?php echo $dddCelular->getOption('label');?>
									</label>
									<div class="row">
										<div class="col-md-1">
											<?php
											echo $this->formInput($dddCelular);
											echo $this->formElementErrors($dddCelular);
											?>
										</div>
									</div>
								</div>

								<div class="form-group">
									<label for="celular">
										<?php echo $celular->getOption('label');?>
									</label>
									<div class="row">
										<div class="col-md-2">
											<?php 
											echo $this->formInput($celular);
											echo $this->formElementErrors($celular);
											?>
										</div>
									</div>
								</div>

								<div class="form-group">
									<label for="dddFax">
										<?php echo $dddFax->getOption('label');?>
									</label>
									<div class="row">
										<div class="col-md-1">
											<?php
											echo $this->formInput($dddFax);
											echo $this->formElementErrors($dddFax);
											?>
										</div>
									</div>
								</div>

								<div class="form-group">
									<label for="fax">
										<?php echo $fax->getOption('label');?>
									</label>
									<div class="row">
										<div class="col-md-2">
											<?php
											echo $this->formInput($fax);
											echo $this->formElementErrors($fax);
											?>
										</div>
									</div>
								</div>

								<div class="form-group">
									<label for="url">
										<?php echo $url->getOption('label');?>
									</label>
									<div class="row">
										<div class="col-md-5">
											<?php
											echo $this->formInput($url);
											echo $this->formElementErrors($url);
											?>
										</div>
									</div>										
								</div>
								<div class="form-group">
									<label for="email">
										<?php echo $email->getOption('label');?>
									</label>
									<div class="row">
										<div class="col-md-4">
											<?php
											echo $this->formElement($email);
											echo $this->formElementErrors($email);
											?>	
										</div>
									</div>									
								</div>

                                <div class="form-group">
                                    <label for="foto" class="foto">
                                        <?php
                                        echo $foto->getOption('label');
                                        ?>
                                    </label>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <?php
                                            echo $this->formElement($foto);
                                            echo $this->formElementErrors($foto);
                                            ?>
                                        </div>
                                    </div>
                                </div>

								<div class="form-group">
									<label for="situacao">
										<?php 
										echo $situacao->getOption('label');
										?>
									</label>
									<div class="row">
										<div class="col-md-3">
											<?php
											echo $this->formSelect($situacao);
											echo $this->formElementErrors($situacao);
											?>	
										</div>
									</div>										
								</div>

								<br>
								
									<div class="form-group">
										<div class="row">
											<div class="col-md-3">
												<?php
												$enviar = $this->form->get('submit');
				    							echo $this->formElement($enviar);
				    							?>			    					
											</div>
										</div>										
			    					</div>
		    					

								
		    				<?php
							echo $this->form()->closeTag();
							?>
							</div>										
			    		</div>
					</div>	
				</div>  					
			</div>
		</div>
	</div>
</div>
<?php
echo $this->headLink()->prependStylesheet($this->basePath() . '/componentes/chosen/chosen.css');                      
echo $this->headScript()->prependFile($this->basePath() . '/componentes/chosen/chosen.jquery.min.js', 'text/javascript');
echo $this->headScript()->prependFile($this->basePath() 
	. '/componentes/jquery.masked-input/jquery.maskedinput.min.js');
?>
<script type="text/javascript">
    var config = {
      '.chosen-select'           : {},
      '.chosen-select-deselect'  : {allow_single_deselect:true},
      '.chosen-select-no-single' : {disable_search_threshold:10},
      '.chosen-select-no-results': {no_results_text:'Oops, nada foi encontrado!'},
      '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {    	
    	$(selector).chosen(config[selector]);
    }
    $(document).ready(function() {	
		//$(".vendedor").before("<div style='display: none;' class='carregandovend'>Carregando...</div>");
		//$(".vendedor").after("<a href='#modal' class='btn2 submit cadnovo'>Cadastrar Novo</a><br/>");


		jQuery(function($){       		
       		$(".cpf").mask("999.999.999-99");
       		$(".dataNasc").mask("99-99-9999");
       		$(".cep").mask("99999-999");

		});
		
		var last_cep = 0;

		$('.cep').on('keyup', function(){
            var cep = $.trim($('.cep').val()).replace('_','');
            if(cep.length >= 9){
                if(cep != last_cep){                	
                    busca();
                    last_cep = cep;
                }
            }            
        }); 	

        function busca(){        	
        	var cep = $('.cep').val();
        	$.ajax({
        		url: '/core/cep/index/value/' + cep,
        		dataType: "json",   		
        		beforeSend : function(){
        			$(".ceploading").show();
        		},
        		success : function(data){
        			$(".cidade").val("");
        			$(".logradouro").val("");
        			$(".bairro").val("");        				
        			$('.uf').val('').trigger('chosen:updated');
        			$('.tipoLogradouro').val('').trigger('chosen:updated');
        			//$('.uf').find('option:first-child').prop('selected', true).end().trigger('liszt:updated');
        			if (typeof data.length == "undefined"){
        				//limpando os dados
        						
        				if (data.id){        				
	        				// console.log(data.id);	
	        			}
	        			if (data.cep){
	        				// console.log(data.cep);	
	        			}
	        			if (data.nome){
	        				$(".cidade").val(data.nome);
	        				//$(".logradouro").focus();        				
	        				$(".tipoLogradouro").trigger('chosen:activate');
	        			}
	        			if (data.cidade){
	        				$(".cidade").val(data.cidade);        				
	        			}
	        			if (data.logradouro){
	        				$(".logradouro").val(data.logradouro);
	        				$(".numero").focus();
	        			}
	        			if (data.bairro){
	        				$(".bairro").val(data.bairro);
	        			}
	        			if (data.tipoLogradouro){

	        			}
	        			if (data.uf){

	        			}   
	        			if (data.nomeSemAcento){
	        				
	        			} 
	        			if (data.idEstado){	        				
	        				//tem estado escolher o estado no select :D		        				
	        				$('.uf').val(data.idEstado).trigger('chosen:updated');
	        			}
	        			if (data.idTipoLogradouro) {
	        				$('.tipoLogradouro').val(data.idTipoLogradouro).trigger('chosen:updated');
	        			}
        			} else {
        				decisao = confirm("CEP! Não encontrado na base de dados!, Deseja digitar novamente o CEP? Clique no botão OK");
						if (decisao){
							$(".cep").val("");
						    $(".cep").focus();
						    last_cep = 0;
						} else {
						    $(".logradouro").focus();
						}        				
        			}        			        			
        		},
        		complete: function(){        			
        			$(".ceploading").hide();
        		}
        	});
        	
        }

		$(".novo").click(function(event){
			event.preventDefault();
			$("#modal").modal();
			endereco = $(this).attr('href');
			$.ajax({
	  			url: endereco,
	  			beforeSend: function() {
	  				$('.dados').hide();
	  				$('.loading').show();
					//mostrar o loading
				},
	  			success: function(data) {
	  				$('.loading').hide();
	    			$('.dados').html(data);
	    			$('.dados').show();
	    			alert('Dados carregado.');    			
	  			}
			});
		});
	});	
</script>