<div class="row">
	<ol class="breadcrumb">
		<li><a href="/">Ínicio</a></li>
	  	<li><a href="/portal/funcionario">Cadastro de Funcionários</a></li>
	  	<li class="active">Salvar</li>
	</ol>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
  			<h1><i class="icon icon-group"></i> Cadastro <small>de funcionários</small></h1>
		</div>
	</div>	
</div>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
  			<div class="panel-heading">
  				<b>Salvar</b>
  			</div>  			
			<div class="row">			
				<div class="col-md-12 p-20">
					<?php
					echo $this->form()->openTag($form);
					$id = $this->form->get('id');
					$refCodPessoaFj = $this->form->get('refCodPessoaFj');					
					echo $this->formInput($id);
					?>	  				
					<div class="form-group">
						<div class="row">
							<div class="col-md-3">
								<label for="refCodPessoaFj">
									<?php
									echo $refCodPessoaFj->getOption('label');
									?>
								</label>								
								<?php
								echo $this->formSelect($refCodPessoaFj);
								echo $this->formElementErrors($refCodPessoaFj);
								?>
							</div>
							<div class="col-md-4">
								<br>
								<a href="/usuario/fisica/save/ajax/1" class="btn btn-primary novo">
									<i class="icon icon-plus"></i> Nova Pessoa Física
								</a>
							</div>							
						</div>
					</div>					
					<?php
					$enviar = $this->form->get('submit');
    				echo $this->formElement($enviar);
					echo $this->form()->closeTag();
					?>
	    		</div>
			</div>			
		</div>
	</div>
</div>
<aside id="modal">
	<header>
		<h2>Cadastrar Pessoa Física</h2>
	</header>
	<div class="loading">
		<br/><i class='glyphicon icon-spinner icon-spin icon-large'></i> Aguarde Carregando.
	</div>
	<div class="dados" style="display:none;">						
	</div>
</aside>
<?php
echo $this->headLink()->prependStylesheet($this->basePath() . '/componentes/chosen/chosen.min.css');                      
echo $this->headScript()->prependFile($this->basePath() . '/componentes/chosen/chosen.jquery.min.js', 'text/javascript');
?>
<script type="text/javascript">
    var config = {
      '.chosen-select'           : {},
      '.chosen-select-deselect'  : {allow_single_deselect:true},
      '.chosen-select-no-single' : {disable_search_threshold:10},
      '.chosen-select-no-results': {no_results_text:'Oops, nada foi encontrado!'},
      '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {    	
    	$(selector).chosen(config[selector]);
    }
    $(document).ready(function() {	
		//$(".vendedor").before("<div style='display: none;' class='carregandovend'>Carregando...</div>");
		//$(".vendedor").after("<a href='#modal' class='btn2 submit cadnovo'>Cadastrar Novo</a><br/>");
		$(".novo").click(function(event){
			event.preventDefault();
			$("#modal").modal();
			endereco = $(this).attr('href');
			$.ajax({
	  			url: endereco,
	  			beforeSend: function() {
	  				$('.dados').hide();
	  				$('.loading').show();
					//mostrar o loading
				},
	  			success: function(data) {
	  				$('.loading').hide();
	    			$('.dados').html(data);
	    			$('.dados').show();
	    			alert('Dados carregado.');    			
	  			}
			});
		});
	});	
</script>