<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'application/index/index'    => __DIR__ . '/view/application/index/index.phtml',
    'error/404'                  => __DIR__ . '/view/error/404.phtml',
    'error/index'                => __DIR__ . '/view/error/index.phtml',
    'layout/layout'              => __DIR__ . '/view/layout/layout.phtml',
    'partials/paginator/control' => __DIR__ . '/view/partials/paginator/control.phtml',
);
