<?php						
if (count($this->dados) > 0):
	foreach ($this->dados as $funcionario):
	?>
		<tr>
			<td>
				<?php 
				echo $funcionario->getId();
				?>				
			</td>
			<td>
				<?php
				echo $funcionario->getFisica()->getNome();
				?>
			</td>
			<td>
				<?php
				if ($funcionario->getAtivo()){
					$situacao = 'Ativo';
					$label = 'success';
				} else {
					$situacao = 'Inativo';
					$label = 'default';
				}
				?>
				<span class="label label-<?php echo $label;?>"><?php echo $situacao;?></span>
			</td>					  									  				
			<td>
				<a href="/drh/funcionario/ver/id/<?php echo $funcionario->getId()?>" class="btn btn-info">
					<i class="icon icon-list"></i> Ver detalhes
				</a>
				<a href="/drh/funcionario/save/id/<?php echo $funcionario->getId()?>" class="btn btn-primary">
					<i class="icon icon-pencil"></i> Editar
				</a>
				<a href="/drh/funcionario/delete/id/<?php echo $funcionario->getId()?>" class="btn btn-danger delete">
					<i class="icon icon-trash"></i> Apagar
				</a>
			</td>
		</tr>
	<?php
	endforeach;
else:
?>
	<tr class="warning">
		<td colspan="4" class="text-center">
			<b>Nenhum registro encontrado</b>
		</td>
	</tr>
<?php
endif;
?>