<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('I-Educar 2.0 - Sistema de Gerenciamento Escolar')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/ieducar-logo.png') ?>" alt="i-Educar 2.0"/>&nbsp;<?php echo $this->translate('i-Educar') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="<?php echo $this->url('home') ?>"><i class="icon icon-home"></i> <?php echo $this->translate('Home') ?></a>
                        </li>
                        <?php
                        if ($user = $this->identity()) {
                        ?>
                            
                            
                            
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                  <i class="icon icon-pencil"></i> i-Escola <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">Apresentação</a>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a href="#">Cadastros...</a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="#">Instituição</a>
                                            </li>                                            
                                            <li class="dropdown-submenu">
                                                <a href="#">Regras de avaliação..</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="#">Listar Regras</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Fórmulas de cálculo de média</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Tabelas de arrendondamento</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li class="dropdown-submenu">
                                                <a href="#">Cursos..</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="#">Cadastrar</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Habilitação</a>
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a href="#">Servidores...</a>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a href="#">Movimentação...</a>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a href="#">Administrativo...</a>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a href="#">Relatórios...</a>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a href="#">Documentos...</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                  <i class="icon icon-book"></i> i-Biblioteca <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">Apresentação</a>
                                    </li>                                  
                                </ul>
                            </li>
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                  <i class="icon icon-group"></i> Administração <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">Cadastro de Setores</a>
                                    </li> 
                                    <li>
                                        <a href="#">Cadastro de Funcionários</a>                                        
                                    </li>                                 
                                </ul>
                            </li>
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="icon icon-group"></i> Pessoa F/J <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="/usuario/fisica">Pessoa Física</a>
                                    </li>
                                    <li>
                                        <a href="/usuario/juridica">Pessoa Jurídica</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                  <i class="icon icon-cogs"></i> Configurações <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="/auth/resource">Recursos</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="/auth/index/logout">
                                    <i class="icon icon-signout"></i> Sair
                                </a>
                            </li>
                        <?php
                        }
                        ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <?php if(isset($flashMessages)):             
            $class = key((array) $flashMessages[0]);            
        ?>
            <div class="container">                                
                <div class="row">
                    <div class="alert alert-<?php if ($class == 'success') { echo "success"; } else if ($class == 'error'){ echo 'danger'; }?>">
                            <?php                             
                            foreach ($flashMessages as $key => $flashMessage) : ?>
                                <?php                  
                                $message = current((array) $flashMessage);               
                                echo $message;?>                            
                            <?php endforeach; ?>         
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <div class="container">            
            <?php echo $this->content; ?>            
        </div> <!-- /container -->        
        <div class="container">
            <div class="row">
                <hr>
                <footer>
                    <p>&copy; <?php echo date('Y') ?> by Eduardo Junior.com. <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>    
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
