<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('i-Educar 2.0 - Sistema de Gerenciamento Escolar')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() 
                            . '/componentes/jquery-ui-1.10.4.custom/css/cupertino/jquery-ui-1.10.4.custom.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/componentes/jquery-ui-1.10.4.custom/js/jquery-ui-1.10.4.custom.min.js')
            ->prependFile($this->basePath() . '/js/modernizr.custom.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>        

        <script type="text/javascript">
        var initDatepicker = function() {
            $('input[type=date]').each(function() {
                var $input = $(this);
                $input.datepicker({
                    minDate: $input.attr('min'),
                    maxDate: $input.attr('max'),
                    changeMonth: true,
                    changeYear: true,                    
                    dateFormat: 'dd-mm-yy',
                    dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
                    dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
                    dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
                    monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto',
                    'Setembro','Outubro','Novembro','Dezembro'],
                    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
                    nextText: 'Próximo',
                    prevText: 'Anterior',
                    yearRange: "1950:<?php echo date('Y');?>"
                });
            });
        };
     
        if(!Modernizr.inputtypes.date){
            $(document).ready(initDatepicker);
        };
        </script>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/ieducar-logo.png') ?>" alt="i-Educar 2.0"/>&nbsp;<?php echo $this->translate('i-Educar') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="<?php echo $this->url('home') ?>"><i class="icon icon-home"></i> <?php echo $this->translate('Home') ?></a>
                        </li>
                        <?php                        
                        if ($user = $this->identity()) {
                        ?>
                            
                            
                            
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                  <i class="icon icon-pencil"></i> i-Escola <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="/escola">Apresentação</a>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a href="#">Cadastros...</a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="/escola/instituicao">Instituição</a>
                                            </li>
                                            <li class="dropdown-submenu">
                                                <a href="#">Cursos..</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="/escola/curso">Cadastrar</a>
                                                    </li>
                                                    <li>
                                                        <a href="/escola/habilitacao">Habilitação</a>
                                                    </li>
                                                    <li>
                                                        <a href="/escola/tipo-regime">Tipo de Regime</a>
                                                    </li>
                                                    <li>
                                                        <a href="/escola/tipo-ensino">Tipo de Ensino</a>
                                                    </li>
                                                    <li>
                                                        <a href="/escola/nivel-ensino">Nível Ensino</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li class="dropdown-submenu">
                                                <a href="#"><i class="glyphicon glyphicon-cog"></i>
                                                    Regras de avaliação..</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="/escola/regra-avaliacao">
                                                            <i class="icon icon-cog"></i>
                                                            Listar Regras</a>
                                                    </li>
                                                    <li>
                                                        <a href="/escola/formula-media">
                                                            <i class="glyphicon glyphicon-edit"></i>
                                                            Fórmulas de Cálculo de Média</a>
                                                    </li>
                                                    <li>
                                                        <a href="/escola/tabela-arredondamento">
                                                            <i class="icon icon-table"></i>
                                                            Tabelas de Arredondamento</a>
                                                    </li>
                                                </ul>
                                            </li>

                                            <li class="dropdown-submenu">
                                                <a href="#">Componentes curriculares</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="#">Listar componentes</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Áreas de conhecimento</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Tipos de dispensa</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li class="dropdown-submenu">
                                                <a href="#">Séries</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="#">Cadastrar</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Escola-Série</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li>
                                                <a href="#">Sequência de Enturmação</a>                                                
                                            </li>
                                            <li>
                                                <a href="#">Módulos</a>
                                            </li>
                                            <li class="dropdown-submenu">
                                                <a href="#">Escola</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="#">Cadastrar</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Localização</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Rede de Ensino</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li class="dropdown-submenu">
                                                <a href="#">Infra Estrutura</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="#">Prédios</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Comodo Prédio</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Função Cômodo</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li class="dropdown-submenu">
                                                <a href="#">Turma</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="#">Cadastrar</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Tipo</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li class="dropdown-submenu">
                                                <a href="#">Calendário Letivo</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="#">Calendários</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Motivos</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li>
                                                <a href="#">Deficiências</a>
                                            </li>
                                            <li class="dropdown-submenu">
                                                <a href="#">Aluno</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="#">Alunos</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Benefícios</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Religião</a>
                                                    </li>
                                                    <li>
                                                        <a href="/usuario/raca">Raça</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li>
                                                <a href="#">Tipos de Ocorrências</a>
                                            </li>
                                            <li class="dropdown-submenu">
                                                <a href="#">Material Didático</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="#">Materiais</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Tipo Material</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li>
                                                <a href="#">Tipo de Transparência</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a href="#">Servidores...</a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="#">Cadastrar</a>
                                            </li>
                                            <li>
                                                <a href="#">Escolaridade</a>
                                            </li>
                                            <li>
                                                <a href="#">Motivo de Afastamento</a>
                                            </li>
                                            <li>
                                                <a href="#">Categoria Níveis</a>
                                            </li>
                                            <li>
                                                <a href="#">Função</a>
                                            </li>
                                            <li class="dropdown-submenu">
                                                <a href="#">Relatórios Servidores..</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="#">Relatórios Professores</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Professores por Disciplina</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Servidores por Nível</a>
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a href="#">Movimentação...</a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="#">Reserva de Vaga</a>
                                            </li>
                                            <li>
                                                <a href="#">Quadro de Horário</a>
                                            </li>
                                            <li>
                                                <a href="#">Enturmação</a>
                                            </li>
                                            <li class="dropdown-submenu">
                                                <a href="#">Faltas/Notas..</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="#">Lançamento por Aluno</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Lançamento por Turma</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li>
                                                <a href="#">Rematrícula Automática</a>
                                            </li>
                                            <li>
                                                <a href="#">Relatório Quadros de Horário</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a href="#">Administrativo...</a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="#">Tipo de Usuário</a>
                                            </li>
                                            <li>
                                                <a href="#">Usuários</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a href="#">Relatórios...</a>
                                        <ul class="dropdown-menu">
                                            <li class="dropdown-submenu">
                                                <a href="#">Mais..</a>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="#">Ficha de Rematrícula</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Registro de Transações Expedidas</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Relatório Alunos Idade x Sexo</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Alunos em Exame</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Ata Resultado Final</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Relatório de alunos por idade</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Registro de Matrículas</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Resultado Final</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Levantamento Alfabetizado e não Alfabetizado</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Alunos Benefícios</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Acompanhamento Mensal</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Levantamento Turma Período</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Demonstração Alunos Defasados Nominal</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Ficha de Leitura Escrita</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Acompanhamento Leitura</a>
                                                    </li>
                                                </ul>
                                            </li>  
                                            <li>
                                                <a href="#">Relação de Alunos ANEEs</a>
                                            </li>
                                            <li>
                                                <a href="#">Quadro Sintético Alunos</a>
                                            </li>
                                            <li>
                                                <a href="#">Alunos ANEEs Instituição</a>
                                            </li>
                                            <li>
                                                <a href="#">Demonstrativo Alunos Defasados</a>
                                            </li>
                                            <li>
                                                <a href="#">Demonstrativo Aluno Defasado Geral</a>
                                            </li>
                                            <li>
                                                <a href="#">Controle Desempenho de Alunos</a>
                                            </li>
                                            <li>
                                                <a href="#">Relatório Mov. Mensal Alunos</a>
                                            </li>
                                            <li>
                                                <a href="#">Relação dos Alunos Enturmados</a>
                                            </li>
                                            <li>
                                                <a href="#">Relação dos Alunos Não Enturmados</a>
                                            </li>
                                            <li>
                                                <a href="#">Quadro Curricular</a>
                                            </li>
                                            <li>
                                                <a href="#">Espelho de Notas Bimestral</a>
                                            </li>
                                            <li>
                                                <a href="#">Espelho de Notas</a>
                                            </li>
                                            <li>
                                                <a href="#">Alunos Matriculados Sintético</a>
                                            </li>
                                            <li>
                                                <a href="#">Documentos Pendentes</a>
                                            </li>                                                                                      
                                        </ul>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a href="#">Documentos...</a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="#">Boletim Escolar</a>
                                            </li>
                                            <li>
                                                <a href="#">Diário de Frequência</a>
                                            </li>
                                            <li>
                                                <a href="#">Diário de Avaliações</a>
                                            </li>
                                            <li>
                                                <a href="#">Histórico Escolar</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                  <i class="icon icon-book"></i> i-Biblioteca <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">Apresentação</a>
                                    </li>                                  
                                </ul>
                            </li>
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                  <i class="icon icon-group"></i> Administração <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="/drh/setor">Cadastro de Setores</a>
                                    </li> 
                                    <li class="dropdown-submenu">
                                        <a href="#">DRH...</a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="/drh/funcionario">Cadastro de Funcionários</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a href="#">Pessoa F/J...</a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="/usuario/fisica">Pessoa Física</a>
                                            </li>
                                            <li>
                                                <a href="/usuario/juridica">Pessoa Jurídica</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>                            
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                  <i class="icon icon-cogs"></i> Configurações <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="/auth/resource"><i class="icon icon-sitemap"></i> Recursos</a>
                                    </li>
                                    <li>
                                        <a href="/auth/role"><i class="icon icon-lock"></i> Permissões</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="/auth/index/logout">
                                    <i class="icon icon-signout"></i> Sair
                                </a>
                            </li>
                        <?php
                        }
                        ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <?php if(isset($flashMessages)):
            $array = (array) $flashMessages[0];
            $class = key($array);
        ?>
            <div class="container">                                
                <div class="row">
                    <div class="alert alert-<?php if ($class == 'success') { echo "success"; } else if ($class == 'error'){ echo 'danger'; }?>">
                            <?php                             
                            foreach ($flashMessages as $key => $flashMessage) : ?>
                                <?php
                                $array = (array) $flashMessage;
                                $message = current($array);
                                echo $message;?>                            
                            <?php endforeach; ?>         
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <div class="container">            
            <?php echo $this->content; ?>
        </div> <!-- /container -->        
        <div class="container">
            <div class="row">
                <hr>
                <footer>
                    <p>&copy; <?php echo date('Y') ?> por
                        <a href="http://www.calangodev.com.br" target="_blank">CalangoDev</a>.
                        <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>    
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
