<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <?php if(isset($flashMessages)):             
            $class = key((array) $flashMessages[0]);            
        ?>
            <div class="page">
                <br>                
                <div class="notices">
                    <div class="bg-color-<?php if ($class == 'success') { echo "green"; } else if ($class == 'error'){ echo 'red'; }?>">
                        <!-- <a href="#" class="close"></a> -->
                        <div class="notice-icon">
                            <h1 id="icon-resize-sample" class="<?php if($class == 'success') { echo 'icon-save'; } else if ($class == 'error') { echo 'icon-blocked';}?>" style="font-size: 16px; color: #fff; "></h1>
                        </div>
                        <div class="notice-image">
                            <h1 id="icon-resize-sample" class="<?php if($class == 'success') { echo 'icon-checkmark'; } else if ($class == 'error') { echo 'icon-thumbs-down';}?>"
                        </div>
                        <div class="notice-header fg-color-yellow">
                            <?php                             
                            foreach ($flashMessages as $key => $flashMessage) : ?>
                                <?php                  
                                $message = current((array) $flashMessage);               
                                echo $message;
                                //echo $flashMessage['success']; ?><br>
                            <?php endforeach; ?>         
                        </div>
                        <!-- <div class="notice-text">Your computer is hacked and is a part of a botnet!</div> -->
                    </div>
                </div>
                
            </div>
        <?php endif; ?>

        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
