
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="/">Ínicio</a></li>
            <li><a href="<?php echo $this->url('drh');?>">DRH</a>

            </li>
            <li>
                <a href="<?php
                echo $this->url('drh/default', array('controller' => 'setor', 'action' => 'index'));?>">
                    Cadastro de Setores </a>
            </li>
            <li class="active">Salvar
            </li>
        </ol>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h1><i class="icon icon-group"></i> Cadastro <small>de Setores</small></h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>Salvar</b>
                </div>

                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                            $this->form->prepare();
                            echo $this->form()->openTag($form);
                            $id = $this->form->get('id');
                            $parentSetor = $this->form->get('parentSetor');
                            $nome = $this->form->get('nome');
                            $sigla = $this->form->get('sigla');
                            $endereco = $this->form->get('endereco');
                            $ativo = $this->form->get('ativo');
                            $nivel = $this->form->get('nivel');
                            echo $this->formInput($id);
                            ?>
                            <br>
                            <div class="form-group">

                                <label for="refCodSetor">
                                    <?php echo $parentSetor->getOption('label'); ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        echo $this->formSelect($parentSetor);
                                        echo $this->formElementErrors($parentSetor);
                                        ?>
                                    </div>
                                </div>

                            </div>

                            <div class="form-group">
                                <label for="nome"><?php echo $nome->getOption('label');?></label>
                                <div class="row">
                                    <div class="col-md-2">
                                        <?php echo $this->formInput($nome);?>
                                        <span class="help-block">
                                            <?php echo $this->formElementErrors($nome);?>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="sigla">
                                    <?php echo $sigla->getOption('label');?>
                                </label>

                                <div class="row">
                                    <div class="col-md-2">
                                        <?php echo $this->formInput($sigla);?>
                                        <span class="help-block">
                                            <?php echo $this->formElementErrors($sigla);?>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="endereco">
                                    <?php echo $endereco->getOption('label');?>
                                </label>

                                <div class="row">
                                    <div class="col-md-6">
                                        <?php echo $this->formElement($endereco);?>
                                        <span class="help-block">
                                            <?php echo $this->formElementErrors($endereco);?>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="ativo"><?php echo $ativo->getOption('label');?></label>

                                <div class="row">
                                    <div class="col-md-2">
                                        <?php echo $this->formSelect($ativo);?>
                                        <span class="help-block">
                                            <?php echo $this->formElementErrors($ativo);?>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="nivel">
                                    <?php echo $nivel->getOption('label');?>
                                </label>

                                <div class="row">
                                    <div class="col-md-2">
                                        <?php echo $this->formSelect($nivel);?>
                                        <span class="help-block">
                                            <?php echo $this->formElementErrors($nivel);?>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <br>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        $enviar = $this->form->get('submit');
                                        echo $this->formElement($enviar);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
echo $this->headLink()->prependStylesheet($this->basePath() . '/componentes/chosen/chosen.css');
echo $this->headScript()->prependFile($this->basePath() . '/componentes/chosen/chosen.jquery.min.js', 'text/javascript');
echo $this->headScript()->prependFile($this->basePath()
    . '/componentes/jquery.masked-input/jquery.maskedinput.min.js');
?>
<script type="text/javascript">
    var config = {
        '.chosen-select'           : {},
        '.chosen-select-deselect'  : {allow_single_deselect:true},
        '.chosen-select-no-single' : {disable_search_threshold:10},
        '.chosen-select-no-results': {no_results_text:'Oops, nada foi encontrado!'},
        '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
        $(selector).chosen(config[selector]);
    }

    $(document).ready(function() {

    });
    //end document ready function
</script>