<?php
if (count($this->dados) > 0):
    $estilos = array('active','warning');
    $this->cycle()->assign($estilos);
    foreach ($this->dados as $juridica):
        ?>
        <tr class="<?php echo $this->cycle()->next();?>">
            <td>
                <?php
                echo $juridica->getId();
                ?>
            </td>
            <td>
                <?php
                echo $juridica->getFantasia();
                ?>
            </td>
            <td>
                <?php
                echo $juridica->getNome();
                ?>
            </td>
            <td>
                <?php
                echo $juridica->getCnpj();
                ?>
            </td>
            <td>
                <?php
                if ($juridica->getSituacao() == 'A'){
                    $situacao = 'Ativo';
                    $label = 'success';
                } else if ($fisica->getSituacao() == 'P') {
                    $situacao = 'Provisório';
                    $label = 'warning';
                } else {
                    $situacao = 'Inativo';
                    $label = 'default';
                }
                ?>
                <span class="label label-<?php echo $label;?>"><?php echo $situacao;?></span>
            </td>
            <td>
                <a href="#<?php echo $juridica->getId()?>"
                   class="btn btn-info btn-detalhes" data-toggle="modal"
                   data-target="#detalhesModal"><i class="icon icon-list"></i> Ver detalhes</a>
                <a href="/usuario/juridica/save/id/<?php echo $juridica->getId()?>"
                   class="btn btn-primary"><i class="icon icon-pencil"></i> Editar</a>
                <a href="/usuario/juridica/delete/id/<?php echo $juridica->getId()?>"
                   class="btn btn-danger delete"><i class="icon icon-trash"></i> Apagar</a>
            </td>
        </tr>
        <?php
    endforeach;
else:
    ?>
    <tr class="warning">
        <td colspan="6" class="text-center">
            <b>Nenhum registro encontrado</b>
        </td>
    </tr>
    <?php
endif;
?>