
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="/">Ínicio</a></li>
            <li><a href="/escola/area-conhecimento">Cadastro de Área de Conhecimento</a></li>
            <li class="active">Salvar</li>
        </ol>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h1><i class="icon icon-group"></i> Cadastro <small>de área de conhecimento</small></h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>Salvar</b>
                </div>

                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                            $this->form->prepare();
                            echo $this->form()->openTag($form);
                            $id = $this->form->get('id');
                            $nome = $this->form->get('nome');
                            $secao = $this->form->get('secao');
                            echo $this->formInput($id);
                            ?>
                            <br>

                            <div class="form-group required">
                                <label for="nome">
                                    <?php
                                    echo $nome->getOption('label');
                                    ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-6">
                                        <?php
                                        echo $this->formInput($nome);
                                        ?>
                                        <span class="help-block">
                                                <?php
                                                echo $this->formElementErrors($nome);
                                                ?>
                                            </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="secao"><?php echo $secao->getOption('label');?></label>
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php echo $this->formInput($secao);?>
                                        <span class="help-block">
                                            <?php echo $this->formElementErrors($secao);?>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <br>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        $enviar = $this->form->get('submit');
                                        echo $this->formElement($enviar);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>