
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="/">Ínicio</a></li>
            <li><a href="/escola/comodo-predio">Cadastro de cômodos dos prédios</a></li>
            <li class="active">Salvar</li>
        </ol>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h1><i class="icon icon-group"></i> Cadastro <small>de Cômodo Prédio</small></h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>Salvar</b>
                </div>

                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                            $this->form->prepare();
                            echo $this->form()->openTag($form);
                            $id = $this->form->get('id');
                            $nome = $this->form->get('nome');
                            $descricao = $this->form->get('descricao');
                            $area = $this->form->get('area');
                            $comodoFuncao = $this->form->get('comodoFuncao');
                            $predio = $this->form->get('predio');
                            echo $this->formInput($id);
                            ?>
                            <br>

                            <div class="form-group required">
                                <label for="predio">
                                    <?php echo $predio->getOption('label');?>
                                </label>
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php echo $this->formSelect($predio);?>
                                        <span class="help-block">
                                            <?php echo $this->formElementErrors($predio);?>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group required">
                                <label for="comodoFuncao"><?php echo $comodoFuncao->getOption('label');?></label>
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php echo $this->formSelect($comodoFuncao);?>
                                        <span class="help-block">
                                            <?php echo $this->formElementErrors($comodoFuncao);?>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group required">
                                <label for="nome">
                                    <?php
                                    echo $nome->getOption('label');
                                    ?>
                                </label>
                                <div class="row">
                                    <div class="col-md-6">
                                        <?php
                                        echo $this->formInput($nome);
                                        ?>
                                        <span class="help-block">
                                                <?php
                                                echo $this->formElementErrors($nome);
                                                ?>
                                            </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="descricao"><?php echo $descricao->getOption('label');?></label>
                                <div class="row">
                                    <div class="col-md-10">
                                        <?php echo $this->formTextArea($descricao);?>
                                        <span class="help-block">
                                            <?php echo $this->formElementErrors($descricao);?>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group required">
                                <label for="area"><?php echo $area->getOption('label');?></label>
                                <div class="row">
                                    <div class="col-md-2">
                                        <?php echo $this->formInput($area);?>
                                        <span class="help-block">
                                            <?php echo $this->formElementErrors($area);?>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            
                            <br>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        $enviar = $this->form->get('submit');
                                        echo $this->formElement($enviar);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<?php
echo $this->headLink()->prependStylesheet($this->basePath() . '/componentes/chosen/chosen.css');
echo $this->headScript()->prependFile($this->basePath() . '/componentes/chosen/chosen.jquery.min.js', 'text/javascript');
echo $this->headScript()->prependFile($this->basePath()
    . '/componentes/jquery.masked-input/jquery.maskedinput.min.js');
?>
<script type="text/javascript">
    var config = {
        '.chosen-select'           : {},
        '.chosen-select-deselect'  : {allow_single_deselect:true},
        '.chosen-select-no-single' : {disable_search_threshold:10},
        '.chosen-select-no-results': {no_results_text:'Oops, nada foi encontrado!'},
        '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
        $(selector).chosen(config[selector]);
    }
</script>
