<div class="row">
    <dl class="dl-horizontal">

        <dt>Nome:</dt>
        <dd><?php echo $data->getNome();?></dd>

        <?php
        if ($data->getDescricao()):
            ?>
            <dt>Descrição:</dt>
            <dd><?php echo $data->getDescricao();?></dd>
            <?php
        endif;
        ?>
        <?php
        if ($data->getEndereco()):
        ?>
            <dt>Endereço:</dt>
            <dd>
                <?php
                echo $data->getEndereco();
                ?>
            </dd>
        <?php
        endif;
        ?>
    </dl>
</div>
