                        <?php
                        if (count($this->dados) > 0):
                            $estilos = array('active','warning');
                            $this->cycle()->assign($estilos);
                            foreach ($this->dados as $tipoRegime):
                                ?>
                                <tr class="<?php echo $this->cycle()->next();?>">
                                    <td>
                                        <?php
                                        echo $tipoRegime->getId();
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                        echo $tipoRegime->getNome();
                                        ?>
                                    </td>

                                    <td>
                                        <?php
                                        if ($tipoRegime->getAtivo()){
                                            $situacao = 'Sim';
                                            $label = 'success';
                                        } else {
                                            $situacao = 'Não';
                                            $label = 'default';
                                        }
                                        ?>
                                        <span class="label label-<?php echo $label;?>"><?php echo $situacao;?></span>
                                    </td>
                                    <td>
                                        <a href="#<?php echo $tipoRegime->getId()?>"
                                           class="btn btn-info btn-detalhes" data-toggle="modal"
                                           data-target="#detalhesModal"><i class="icon icon-list"></i> Ver detalhes</a>
                                        <a href="/escola/tipo-regime/save/id/<?php echo $tipoRegime->getId()?>"
                                           class="btn btn-primary"><i class="icon icon-pencil"></i> Editar</a>
                                        <a href="/escola/tipo-regime/delete/id/<?php echo $tipoRegime->getId()?>"
                                           class="btn btn-danger delete"><i class="icon icon-trash"></i> Apagar</a>
                                    </td>
                                </tr>
                                <?php
                            endforeach;
                        else:
                            ?>
                            <tr class="warning">
                                <td colspan="5" class="text-center">
                                    <b>Nenhum registro encontrado</b>
                                </td>
                            </tr>
                            <?php
                        endif;
                        ?>
 
