
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="/">Ínicio</a></li>
            <li><a href="/escola/componente-curricular-ano-escolar">Cadastro de Componentes Curriculares Ano Escolar</a></li>
            <li class="active">Salvar</li>
        </ol>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h1><i class="icon icon-group"></i> Cadastro <small>de componente curricular ano Escolar</small></h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>Salvar</b>
                </div>

                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                            $this->form->prepare();
                            echo $this->form()->openTag($form);
                            $this->formRadio()->setSeparator('</div><div class="radio">');
                            $id = $this->form->get('id');
                            $cargaHoraria = $this->form->get('cargaHoraria');
                            $serie = $this->form->get('serie');
                            $componenteCurricular = $this->form->get('componenteCurricular');
                            echo $this->formInput($id);
                            ?>
                            <br>

                            <div class="form-group">
                                <label for="cargaHoraria">
                                    <?php
                                    echo $cargaHoraria->getOption('label');
                                    ?>
                                    <span class="help"><?php echo $cargaHoraria->getOption('help');?></span>
                                </label>
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        echo $this->formInput($cargaHoraria);
                                        ?>
                                        <span class="help-block">
                                                <?php
                                                echo $this->formElementErrors($cargaHoraria);
                                                ?>
                                            </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group required">
                                <label for="componenteCurricular">
                                    <?php echo $componenteCurricular->getOption('label');?>
                                    <span class="help"><?php echo $componenteCurricular->getOption('help');?></span>
                                </label>
                                <div class="row">
                                    <div class="col-md-2">
                                        <?php echo $this->formSelect($componenteCurricular);?>
                                        <span class="help-block">
                                            <?php echo $this->formElementErrors($componenteCurricular);?>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group required">
                                <label for="componenteCurricular">
                                    <?php echo $serie->getOption('label');?>
                                    <span class="help"><?php echo $serie->getOption('help');?></span>
                                </label>
                                <div class="row">
                                    <div class="col-md-2">
                                        <?php echo $this->formSelect($serie);?>
                                        <span class="help-block">
                                            <?php echo $this->formElementErrors($serie);?>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <br>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-3">
                                        <?php
                                        $enviar = $this->form->get('submit');
                                        echo $this->formElement($enviar);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
echo $this->headLink()->prependStylesheet($this->basePath() . '/componentes/chosen/chosen.css');
echo $this->headScript()->prependFile($this->basePath() . '/componentes/chosen/chosen.jquery.min.js', 'text/javascript');
echo $this->headScript()->prependFile($this->basePath()
    . '/componentes/jquery.masked-input/jquery.maskedinput.min.js');
?>
<script type="text/javascript">
    var config = {
        '.chosen-select'           : {},
        '.chosen-select-deselect'  : {allow_single_deselect:true},
        '.chosen-select-no-single' : {disable_search_threshold:10},
        '.chosen-select-no-results': {no_results_text:'Oops, nada foi encontrado!'},
        '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
        $(selector).chosen(config[selector]);
    }
</script>